(()=>{
const CFG=window.APRINCAR_GAME_CONFIG;
const COLORS={bg:0xf7f6f2,purple:0x6f5bd7,purple2:0xefeafe,coral:0xf07867,sun:0xf4c95d,leaf:0x65a67a,sky:0x62a6d8,ink:'#242523',muted:'#6f716d',white:0xffffff};
const COLOR_HEX={violet:COLORS.purple,coral:COLORS.coral,sun:COLORS.sun,leaf:COLORS.leaf,sky:COLORS.sky};
class AprincarScene extends Phaser.Scene{
 constructor(){super('main');this.level=1;this.attempts=0;this.sessionStarted=false;this.locked=false;}
 async create(){
  this.cameras.main.setBackgroundColor(COLORS.bg);
  this.add.rectangle(480,52,960,104,COLORS.white).setStrokeStyle(1,0xe2dfd7);
  this.add.text(34,25,'APRINCAR',{fontFamily:'Arial',fontSize:'18px',fontStyle:'bold',color:'#6f5bd7'});
  this.titleText=this.add.text(480,20,CFG.name,{fontFamily:'Arial',fontSize:'26px',fontStyle:'bold',color:COLORS.ink}).setOrigin(.5,0);
  this.levelText=this.add.text(910,28,'Fase 1',{fontFamily:'Arial',fontSize:'16px',fontStyle:'bold',color:'#6f5bd7'}).setOrigin(1,0);
  this.promptText=this.add.text(480,118,'',{fontFamily:'Arial',fontSize:'28px',fontStyle:'bold',color:COLORS.ink,align:'center',wordWrap:{width:820}}).setOrigin(.5,0);
  this.statusText=this.add.text(480,570,'',{fontFamily:'Arial',fontSize:'22px',fontStyle:'bold',color:'#5143a6'}).setOrigin(.5,.5);
  this.starText=this.add.text(32,574,'⭐ 0',{fontFamily:'Arial',fontSize:'20px',fontStyle:'bold',color:'#6f5bd7'});
  this.mascot=this.createMascot(875,520);
  await aprincar.session.start({mode:CFG.mode}); this.sessionStarted=true;
  this.nextRound();
 }
 createMascot(x,y){
  const c=this.add.container(x,y); const body=this.add.ellipse(0,0,92,98,COLORS.purple); const eye1=this.add.circle(-18,-12,7,COLORS.white);const eye2=this.add.circle(18,-12,7,COLORS.white);const p1=this.add.circle(-18,-12,3,0x242523);const p2=this.add.circle(18,-12,3,0x242523);const mouth=this.add.arc(0,8,16,0,180,false,COLORS.coral); c.add([body,eye1,eye2,p1,p2,mouth]); this.tweens.add({targets:c,scaleY:1.04,scaleX:.98,duration:900,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});return c;
 }
 clearRound(){if(this.roundGroup)this.roundGroup.destroy(true);this.roundGroup=this.add.container(0,0);this.statusText.setText('');this.locked=false;this.attempts=0;this.testTargets=[];}
 difficulty(){return Math.min(1,.18+this.level*.045);}
 nextRound(){
  this.clearRound();this.levelText.setText(`Fase ${this.level}`);
  const seed=(Date.now()%100000)+this.level*97;const rng=createSeededRandom(seed);
  if(CFG.mode==='counting') this.setupCounting(generateCountingChallenge({rng,seed,level:this.level,theme:CFG.variant}));
  if(CFG.mode==='color') this.setupColor(generateColorChallenge({rng,seed,level:this.level}));
  if(CFG.mode==='pattern') this.setupPattern(generatePatternChallenge({rng,seed,level:this.level}));
  if(CFG.mode==='letter') this.setupLetter(generateLetterChallenge({rng,seed,level:this.level}));
  if(CFG.mode==='memory') this.setupMemory(generateMemoryChallenge({rng,seed,level:this.level}));
  if(CFG.mode==='handwriting') this.setupHandwriting(generateLetterChallenge({rng,seed,level:this.level}));
  if(CFG.mode==='paint') this.setupPaint();
  window.__APRINCAR_GAME_STATE__={mode:CFG.mode,level:this.level,challenge:this.challenge??null,targets:this.testTargets??[]};
 }
 addCardButton(x,y,w,h,label,value,color=COLORS.white){
  const box=this.add.rectangle(x,y,w,h,color).setStrokeStyle(2,0xe2dfd7).setInteractive({useHandCursor:true});
  const text=this.add.text(x,y,label,{fontFamily:'Arial',fontSize:Math.min(34,h*.42)+'px',fontStyle:'bold',color:color===COLORS.white?COLORS.ink:'#ffffff'}).setOrigin(.5);
  this.roundGroup.add([box,text]);this.testTargets?.push({value,x,y,w,h});this.tweens.add({targets:[box,text],y:`-=5`,duration:160,yoyo:true,paused:true});
  box.on('pointerover',()=>box.setScale(1.04));box.on('pointerout',()=>box.setScale(1));box.on('pointerdown',()=>{box.setScale(.96);});box.on('pointerup',()=>{box.setScale(1);this.choose(value,box);});return box;
 }
 setupCounting(c){
  this.challenge=c;
  if(CFG.variant==='animals'){
   this.promptText.setText('Conte os bichos e escolha a quantidade correta');
   const cols=Math.min(5,Math.ceil(Math.sqrt(c.items.length))); const gap=92; const startX=480-(cols-1)*gap/2; const rows=Math.ceil(c.items.length/cols);
   c.items.forEach((_,i)=>{const col=i%cols,row=Math.floor(i/cols);const x=startX+col*gap,y=240+row*86; const animal=this.add.container(x,y);const body=this.add.ellipse(0,8,58,44,COLORS.leaf);const head=this.add.circle(25,-9,22,0x79bd86);const eye=this.add.circle(31,-13,4,COLORS.white);const dot=this.add.circle(31,-13,2,0x242523);const leg1=this.add.rectangle(-15,34,8,22,COLORS.leaf);const leg2=this.add.rectangle(13,34,8,22,COLORS.leaf);animal.add([body,head,eye,dot,leg1,leg2]);this.roundGroup.add(animal);this.tweens.add({targets:animal,y:y-8,duration:650+100*(i%3),yoyo:true,repeat:-1,ease:'Sine.easeInOut'});});
   const optY=rows>1?485:430;c.options.forEach((n,i)=>this.addCardButton(390+(i-(c.options.length-1)/2)*115,optY,90,66,String(n),n));
  } else if(CFG.variant==='fruit'){
   this.promptText.setText(`Coloque ${c.answer} frutas na cesta`);this.selected=0;
   const basket=this.add.rectangle(480,450,270,110,0xc98749).setStrokeStyle(5,0x8f5b2c);this.roundGroup.add(basket);const count=this.add.text(480,450,'0',{fontFamily:'Arial',fontSize:'44px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5);this.roundGroup.add(count);this.counter=count;
   const fruitCount=Math.min(10,c.answer+3);for(let i=0;i<fruitCount;i++){const x=210+(i%5)*135,y=225+Math.floor(i/5)*100;const fruit=this.add.circle(x,y,28,i%2?COLORS.coral:COLORS.sun).setStrokeStyle(4,0xffffff).setInteractive({useHandCursor:true});this.roundGroup.add(fruit);this.tweens.add({targets:fruit,angle:{from:-5,to:5},duration:600+i*30,yoyo:true,repeat:-1});fruit.on('pointerdown',()=>{if(fruit.getData('picked'))return;fruit.setData('picked',true);this.selected++;this.counter.setText(String(this.selected));this.tweens.add({targets:fruit,x:450+(this.selected%4)*20,y:445,duration:340,ease:'Back.easeIn',onComplete:()=>fruit.setScale(.5)});});}
   const check=this.addCardButton(480,535,190,58,'Conferir','__check__',COLORS.purple);this.challengeInteractiveCheck=()=>this.submitResult(this.selected===c.answer,{selected:this.selected,target:c.answer});check.removeAllListeners('pointerup');check.on('pointerup',()=>this.challengeInteractiveCheck());
  } else {
   this.promptText.setText(`Monte uma torre com ${c.answer} blocos`);this.selected=0;this.blocks=[];
   for(let i=0;i<10;i++){const x=170+(i%5)*145,y=220+Math.floor(i/5)*90;const block=this.add.rectangle(x,y,72,62,[COLORS.purple,COLORS.coral,COLORS.sun,COLORS.leaf,COLORS.sky][i%5]).setStrokeStyle(3,0xffffff).setInteractive({useHandCursor:true});this.roundGroup.add(block);block.on('pointerdown',()=>{if(block.getData('picked'))return;block.setData('picked',true);this.selected++;this.tweens.add({targets:block,x:480,y:480-(this.selected-1)*38,scaleX:.82,scaleY:.58,duration:380,ease:'Back.easeOut'});});}
   const check=this.addCardButton(780,500,150,58,'Conferir','__check__',COLORS.purple);check.removeAllListeners('pointerup');check.on('pointerup',()=>this.submitResult(this.selected===c.answer,{selected:this.selected,target:c.answer}));
  }
 }
 setupColor(c){this.challenge=c;this.promptText.setText(`Leve a peça até a cor ${c.label}`);const targetColor=COLOR_HEX[c.answer];const piece=this.add.circle(180,320,54,targetColor).setStrokeStyle(6,0xffffff).setInteractive({draggable:true,useHandCursor:true});this.input.setDraggable(piece);this.roundGroup.add(piece);const slots=[];c.options.forEach((color,i)=>{const x=430+i*135;const slot=this.add.rectangle(x,320,105,115,COLOR_HEX[color],.22).setStrokeStyle(4,COLOR_HEX[color]);slot.setData('color',color);this.roundGroup.add(slot);slots.push(slot);});this.input.on('drag',(p,o,x,y)=>{o.x=x;o.y=y});this.input.once('dragend',()=>{});piece.on('dragend',()=>{});this.input.on('dragend',(pointer,o)=>{if(o!==piece)return;const hit=slots.find(s=>Phaser.Geom.Intersects.CircleToRectangle(new Phaser.Geom.Circle(piece.x,piece.y,40),s.getBounds()));const ok=!!hit&&hit.getData('color')===c.answer;this.submitResult(ok,{target:c.answer,selected:hit?.getData('color')??null});if(!ok)this.tweens.add({targets:piece,x:180,y:320,duration:300,ease:'Back.easeOut'});});}
 setupPattern(c){this.challenge=c;this.promptText.setText('Qual peça continua o padrão?');const palette=[COLORS.purple,COLORS.coral,COLORS.sun,COLORS.leaf,COLORS.sky];const map={'●':0,'▲':1,'■':2,'◆':3,'★':4};c.sequence.forEach((token,i)=>{const x=210+i*70;const shape=this.addShape(x,280,token,palette[map[token]??0]);this.roundGroup.add(shape);});const q=this.add.text(210+c.sequence.length*70,280,'?',{fontFamily:'Arial',fontSize:'52px',fontStyle:'bold',color:'#6f5bd7'}).setOrigin(.5);this.roundGroup.add(q);c.options.forEach((t,i)=>this.addCardButton(360+i*115,430,90,76,t,t,palette[map[t]??0]));}
 addShape(x,y,token,color){if(token==='●')return this.add.circle(x,y,30,color);if(token==='■')return this.add.rectangle(x,y,58,58,color);if(token==='▲'){const g=this.add.triangle(x,y,0,56,28,0,56,56,color);return g;}if(token==='◆'){const r=this.add.rectangle(x,y,50,50,color);r.setAngle(45);return r;}return this.add.star(x,y,5,18,34,color);}
 setupLetter(c){this.challenge=c;this.promptText.setText(`Encontre a letra ${c.answer}`);const positions=Phaser.Utils.Array.Shuffle([{x:240,y:250},{x:410,y:230},{x:580,y:260},{x:735,y:235},{x:320,y:400},{x:500,y:410},{x:680,y:390}]).slice(0,c.options.length);c.options.forEach((letter,i)=>{const p=positions[i];const circle=this.add.circle(p.x,p.y,54,[COLORS.purple,COLORS.coral,COLORS.sun,COLORS.leaf,COLORS.sky][i%5]).setInteractive({useHandCursor:true});const txt=this.add.text(p.x,p.y,letter,{fontFamily:'Arial',fontSize:'48px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5);this.roundGroup.add([circle,txt]);this.tweens.add({targets:[circle,txt],y:`-=${8+i%3}`,duration:750+i*70,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});circle.on('pointerup',()=>this.choose(letter,circle));});}
 setupMemory(c){this.challenge=c;this.promptText.setText('Encontre todos os pares');this.memoryOpen=[];this.memoryMatched=0;this.memoryMoves=0;const cols=c.pairs<=4?4:c.pairs<=6?4:5;const cardW=115,cardH=92,gapX=135,gapY=112;const rows=Math.ceil(c.cards.length/cols);const startX=480-(cols-1)*gapX/2;const startY=220-(rows-2)*35;c.cards.forEach((card,i)=>{const x=startX+(i%cols)*gapX,y=startY+Math.floor(i/cols)*gapY;const box=this.add.rectangle(x,y,cardW,cardH,COLORS.purple).setStrokeStyle(4,0xffffff).setInteractive({useHandCursor:true});const txt=this.add.text(x,y,'★',{fontFamily:'Arial',fontSize:'40px',color:'#ffffff'}).setOrigin(.5);box.setData('card',card);box.setData('text',txt);this.roundGroup.add([box,txt]);box.on('pointerup',()=>this.flipMemory(box));});}
 flipMemory(box){if(this.locked||box.getData('matched')||box.getData('open'))return;const card=box.getData('card'),txt=box.getData('text');box.setData('open',true);this.tweens.add({targets:[box,txt],scaleX:0,duration:100,yoyo:true,onYoyo:()=>{box.setFillStyle(COLORS.white);txt.setColor(COLORS.ink);txt.setText(card.value);}});this.memoryOpen.push(box);if(this.memoryOpen.length===2){this.memoryMoves++;this.locked=true;const[a,b]=this.memoryOpen;const same=a.getData('card').pairId===b.getData('card').pairId;this.time.delayedCall(480,async()=>{if(same){a.setData('matched',true);b.setData('matched',true);this.memoryMatched++;this.celebrateAt((a.x+b.x)/2,(a.y+b.y)/2);if(this.memoryMatched===this.challenge.pairs){await this.submitResult(true,{moves:this.memoryMoves,pairs:this.challenge.pairs});}}else{for(const x of[a,b]){x.setData('open',false);x.setFillStyle(COLORS.purple);x.getData('text').setText('★').setColor('#ffffff');}await this.recordEvidence(false,{memoryMismatch:true});}this.memoryOpen=[];this.locked=false;});}}
 setupHandwriting(c){this.challenge=c;this.challenge.answer=c.answer;this.promptText.setText(`Desenhe a letra ${c.answer}`);this.add.text(235,330,c.answer,{fontFamily:'Arial',fontSize:'250px',fontStyle:'bold',color:'#efeafe'}).setOrigin(.5);const zone=this.add.rectangle(590,335,470,350,0xffffff).setStrokeStyle(4,0xded5ff).setInteractive();this.roundGroup.add(zone);const guide=this.add.text(590,335,c.answer,{fontFamily:'Arial',fontSize:'250px',fontStyle:'bold',color:'#f0ecff'}).setOrigin(.5);this.roundGroup.add(guide);this.drawGraphics=this.add.graphics();this.roundGroup.add(this.drawGraphics);this.strokes=[];let current=null;zone.on('pointerdown',p=>{current=[];this.strokes.push(current);current.push(this.normPoint(p,zone));this.drawGraphics.lineStyle(12,COLORS.purple,1);this.drawGraphics.beginPath();this.drawGraphics.moveTo(p.x,p.y);});zone.on('pointermove',p=>{if(!p.isDown||!current)return;current.push(this.normPoint(p,zone));this.drawGraphics.lineTo(p.x,p.y);this.drawGraphics.strokePath();});this.input.on('pointerup',()=>{current=null;});const check=this.addCardButton(790,535,170,58,'Conferir','__check__',COLORS.purple);check.removeAllListeners('pointerup');check.on('pointerup',async()=>{const result=await aprincar.capability.request('handwriting.evaluate',{symbol:c.answer,strokes:this.strokes});const ok=!!result?.recognized;await this.submitResult(ok,{handwriting:result,symbol:c.answer});});}
 normPoint(p,zone){const b=zone.getBounds();return{x:(p.x-b.left)/b.width,y:(p.y-b.top)/b.height,t:Date.now()};}
 setupPaint(){this.promptText.setText('Crie do seu jeito — não existe resposta errada');const canvas=this.add.rectangle(500,335,690,390,0xffffff).setStrokeStyle(3,0xe2dfd7).setInteractive();this.roundGroup.add(canvas);const palette=[COLORS.purple,COLORS.coral,COLORS.sun,COLORS.leaf,COLORS.sky,0x242523];this.paintColor=palette[0];palette.forEach((color,i)=>{const c=this.add.circle(90,210+i*55,21,color).setInteractive({useHandCursor:true});this.roundGroup.add(c);c.on('pointerup',()=>{this.paintColor=color;});});this.paintGraphics=this.add.graphics();this.roundGroup.add(this.paintGraphics);let drawing=false;canvas.on('pointerdown',p=>{drawing=true;this.paintGraphics.lineStyle(10,this.paintColor,1);this.paintGraphics.beginPath();this.paintGraphics.moveTo(p.x,p.y);});canvas.on('pointermove',p=>{if(!drawing||!p.isDown)return;this.paintGraphics.lineTo(p.x,p.y);this.paintGraphics.strokePath();});this.input.on('pointerup',()=>drawing=false);const save=this.addCardButton(800,540,160,56,'Guardar desenho','__save__',COLORS.purple);save.removeAllListeners('pointerup');save.on('pointerup',async()=>{await this.recordEvidence(true,{creative:true});this.statusText.setText('Sua criação foi guardada como uma conquista ✨');this.celebrateAt(780,500);});}
 choose(value,source){if(this.locked)return;this.submitResult(value===this.challenge.answer,{selected:value,target:this.challenge.answer,sourceX:source?.x});}
 async recordEvidence(ok,metadata={}){this.attempts++;return aprincar.evidence.submit({skillId:CFG.skillId,result:ok?'success':'failure',independent:true,assistance:'none',difficulty:this.challenge?.difficulty??.35,confidence:ok?.92:.8,attempts:this.attempts,metadata:{level:this.level,...metadata}});}
 async submitResult(ok,metadata={}){if(this.locked)return;this.locked=true;if(window.__APRINCAR_GAME_STATE__)window.__APRINCAR_GAME_STATE__.lastResult=ok?'success':'failure';await this.recordEvidence(ok,metadata);if(ok){this.statusText.setText('Isso! Você encontrou um caminho ✨');await aprincar.rewards.request({reason:`${CFG.mode}-round`,amount:2});this.celebrateAt(480,500);this.tweens.add({targets:this.mascot,angle:{from:-6,to:6},scale:1.12,duration:140,yoyo:true,repeat:3});this.time.delayedCall(900,()=>{this.level++;this.nextRound();});}else{this.statusText.setText('Quase! Tente de outro jeito.');this.cameras.main.shake(120,.003);this.locked=false;}}
 celebrateAt(x,y){const particles=[];for(let i=0;i<18;i++){const p=this.add.circle(x,y,4,[COLORS.purple,COLORS.coral,COLORS.sun,COLORS.leaf,COLORS.sky][i%5]);particles.push(p);this.tweens.add({targets:p,x:x+Phaser.Math.Between(-150,150),y:y+Phaser.Math.Between(-130,20),alpha:0,scale:0,duration:650+Phaser.Math.Between(0,220),ease:'Cubic.easeOut',onComplete:()=>p.destroy()});}this.starText.setText(`⭐ ${Math.max(0,(this.level-1)*2+2)}`);}
}
new Phaser.Game({type:Phaser.AUTO,width:960,height:640,parent:'game',backgroundColor:'#f7f6f2',scene:[AprincarScene],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},input:{activePointers:3},render:{antialias:true}});
})();
