export const games = [
  {
    slug: 'counting-animals',
    id: 'aprincar.counting-animals',
    name: 'Conte os Bichos',
    description: 'Conte bichos animados e escolha a quantidade correta.',
    mode: 'counting',
    variant: 'animals',
    familyId: 'quantities',
    objective: 'Perceber uma quantidade, contar e relacionar o total ao numeral correto.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'none',
      motorDemand: 'low',
      scaffolding: 'Poucas quantidades primeiro; dificuldade cresce por fase.',
    },
    skillId: 'math.counting.1-10',
    ages: [4, 7],
    interests: ['math', 'counting', 'animals'],
    playType: 'learning',
    permissions: [],
    experience: {
      fantasy: 'Safari dos bichos',
      mechanic: 'tap-count',
      interaction: 'tap',
      progression: { maxLevel: 5, adaptive: true },
      learningSignals: ['accuracy', 'independentSuccess'],
    },
  },
  {
    slug: 'fruit-basket',
    id: 'aprincar.fruit-basket',
    name: 'Cesta de Frutas',
    description: 'Escolha a quantidade pedida e leve as frutas até a cesta.',
    mode: 'counting',
    variant: 'fruit',
    familyId: 'quantities',
    objective: 'Formar uma quantidade pedida manipulando objetos concretos.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'none',
      motorDemand: 'medium',
      scaffolding: 'Tap e drag equivalentes; objetos grandes e contagem visual.',
    },
    skillId: 'math.counting.1-10',
    ages: [4, 7],
    interests: ['math', 'counting', 'fruits'],
    playType: 'learning',
    permissions: [],
    experience: {
      fantasy: 'Feira da cesta',
      mechanic: 'drag-into-basket',
      interaction: 'drag',
      progression: { maxLevel: 5, adaptive: true },
      learningSignals: ['quantity', 'coordination'],
    },
  },
  {
    slug: 'block-tower',
    id: 'aprincar.block-tower',
    name: 'Torre de Blocos',
    description: 'Monte torres com a quantidade certa de blocos.',
    mode: 'counting',
    variant: 'blocks',
    familyId: 'quantities',
    objective: 'Construir uma coleção com quantidade exata e acompanhar a contagem.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'none',
      motorDemand: 'medium',
      scaffolding: 'Tap e drag equivalentes; pilha compacta e reversível.',
    },
    skillId: 'math.counting.1-10',
    ages: [4, 7],
    interests: ['math', 'counting', 'construction'],
    playType: 'learning',
    permissions: [],
    experience: {
      fantasy: 'Obra da torre',
      mechanic: 'stack',
      interaction: 'drag',
      progression: { maxLevel: 5, adaptive: true },
      learningSignals: ['quantity', 'sequencing'],
    },
  },
  {
    slug: 'color-match',
    id: 'aprincar.color-match',
    name: 'Mundo das Cores',
    description: 'Leve cada peça até a cor correspondente.',
    mode: 'color',
    variant: 'colors',
    familyId: 'creative',
    objective: 'Classificar visualmente objetos por cor.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'none',
      motorDemand: 'medium',
      scaffolding: 'Alvos grandes, pareamento visual e retry imediato.',
    },
    skillId: 'perception.colors.match',
    ages: [2, 5],
    interests: ['colors', 'logic', 'drag'],
    playType: 'learning',
    permissions: [],
    experience: {
      fantasy: 'Ateliê das cores',
      mechanic: 'drag-match',
      interaction: 'drag',
      progression: { maxLevel: 5, adaptive: true },
      learningSignals: ['classification', 'accuracy'],
    },
  },
  {
    slug: 'pattern-play',
    id: 'aprincar.pattern-play',
    name: 'Trem dos Padrões',
    description: 'Descubra qual peça continua cada sequência.',
    mode: 'pattern',
    variant: 'train',
    familyId: 'logic',
    objective: 'Identificar a regra de uma sequência e prever o próximo elemento.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'none',
      motorDemand: 'low',
      scaffolding: 'Começa em padrões AB e progride para sequências maiores.',
    },
    skillId: 'logic.patterns.ab',
    secondarySkills: ['logic.patterns.abc'],
    ages: [4, 8],
    interests: ['logic', 'patterns'],
    playType: 'learning',
    permissions: [],
    experience: {
      fantasy: 'Trem dos padrões',
      mechanic: 'tap-sequence',
      interaction: 'tap',
      progression: { maxLevel: 5, adaptive: true },
      learningSignals: ['sequencing', 'prediction'],
    },
  },
  {
    slug: 'letter-hunt',
    id: 'aprincar.letter-hunt',
    name: 'Caça às Letras',
    description: 'Encontre letras em movimento e avance por desafios.',
    mode: 'letter',
    variant: 'hunt',
    familyId: 'literacy',
    objective: 'Reconhecer visualmente uma letra entre alternativas.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'emerging',
      motorDemand: 'low',
      scaffolding: 'Uma letra-alvo por rodada com alternativas grandes.',
    },
    skillId: 'literacy.letter.recognition',
    ages: [4, 7],
    interests: ['letters', 'literacy'],
    playType: 'learning',
    permissions: [],
    experience: {
      fantasy: 'Caça ao tesouro das letras',
      mechanic: 'tap-chase',
      interaction: 'tap',
      progression: { maxLevel: 5, adaptive: true },
      learningSignals: ['recognition', 'attention'],
    },
  },
  {
    slug: 'write-a',
    id: 'aprincar.write-a',
    name: 'Ateliê de Letras',
    description: 'Desenhe letras com apoio visual que diminui conforme você avança.',
    mode: 'handwriting',
    variant: 'letters',
    familyId: 'literacy',
    objective: 'Praticar o formato gráfico de letras com apoio visual progressivo.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'emerging',
      motorDemand: 'fine',
      scaffolding: 'Guia visual forte no início e redução gradual por fase.',
    },
    answers: ['A', 'B', 'V', 'R', 'T'],
    skillId: 'writing.trace-letter',
    ages: [4, 7],
    interests: ['letters', 'writing'],
    playType: 'practice',
    permissions: ['handwriting'],
    experience: {
      fantasy: 'Escola de escrita',
      mechanic: 'trace',
      interaction: 'draw',
      progression: { maxLevel: 5, adaptive: true },
      learningSignals: ['strokeOrder', 'shape'],
    },
  },
  {
    slug: 'paint-free',
    id: 'aprincar.paint-free',
    name: 'Pintura Livre',
    description: 'Desenhe, pinte e experimente sem resposta certa ou errada.',
    mode: 'paint',
    variant: 'creative',
    familyId: 'creative',
    objective: 'Explorar expressão visual sem resposta única.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'none',
      motorDemand: 'fine',
      scaffolding: 'Sem resposta errada; ferramentas grandes e criação livre.',
    },
    skillId: 'creativity.visual-expression',
    ages: [2, 10],
    interests: ['paint', 'creative'],
    playType: 'creative',
    permissions: ['storage'],
    experience: {
      fantasy: 'Estúdio de pintura',
      mechanic: 'free-draw',
      interaction: 'draw',
      progression: { maxLevel: 5, adaptive: true },
      learningSignals: ['exploration', 'expression'],
    },
  },
  {
    slug: 'memory-animals',
    id: 'aprincar.memory-animals',
    name: 'Memória dos Bichos',
    description: 'Encontre pares em tabuleiros que crescem automaticamente.',
    mode: 'memory',
    variant: 'animals',
    familyId: 'logic',
    objective: 'Usar memória visual para localizar pares.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'none',
      motorDemand: 'low',
      scaffolding: 'Tabuleiro cresce gradualmente e retry não pune exploração.',
    },
    skillId: 'perception.visual.discrimination',
    ages: [3, 7],
    interests: ['memory', 'animals', 'logic'],
    playType: 'practice',
    permissions: [],
    experience: {
      fantasy: 'Reserva dos pares',
      mechanic: 'flip-pairs',
      interaction: 'tap',
      progression: { maxLevel: 5, adaptive: true },
      learningSignals: ['workingMemory', 'accuracy'],
    },
  },
  {
    slug: 'space-shapes-3d',
    id: 'aprincar.space-shapes-3d',
    name: 'Formas no Espaço 3D',
    description: 'Gire sólidos em 3D e reconheça suas formas.',
    mode: 'three',
    variant: 'geometry',
    familyId: 'spatial',
    objective: 'Reconhecer sólidos a partir de diferentes pontos de vista.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'emerging',
      motorDemand: 'medium',
      scaffolding: 'Poucos sólidos por rodada, rotação livre e feedback visual.',
    },
    skillId: 'math.geometry.solids',
    ages: [5, 9],
    interests: ['geometry', '3d', 'exploration'],
    playType: 'learning',
    permissions: [],
    experience: {
      fantasy: 'Missão espacial',
      mechanic: 'rotate-select',
      interaction: 'rotate',
      progression: { maxLevel: 5, adaptive: true },
      learningSignals: ['spatialReasoning', 'recognition'],
    },
  },

  {
    slug: 'prewriting-trails',
    id: 'aprincar.prewriting-trails',
    name: 'Caminhos da Escrita',
    description: 'Siga caminhos com o dedo para treinar linhas, curvas e movimentos da escrita.',
    mode: 'prewriting',
    variant: 'trails',
    familyId: 'literacy',
    objective: 'Controlar traços básicos e curvas antes da escrita convencional.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'none',
      motorDemand: 'fine',
      scaffolding: 'Caminhos largos, ponto inicial visível e tolerância que diminui gradualmente.',
    },
    skillId: 'motor.prewriting.lines',
    secondarySkills: ['motor.prewriting.curves'],
    ages: [3, 6],
    interests: ['writing', 'motor', 'tracing'],
    playType: 'practice',
    permissions: [],
    experience: {
      fantasy: 'Trilhas do lápis',
      mechanic: 'trace-path',
      interaction: 'draw',
      progression: { maxLevel: 6, adaptive: true },
      learningSignals: ['pathCoverage', 'motorControl'],
    },
  },
  {
    slug: 'print-letters',
    id: 'aprincar.print-letters',
    name: 'Letras de Forma',
    description: 'Trace letras de forma com guias grandes e pratique cada movimento.',
    mode: 'handwriting',
    variant: 'print',
    familyId: 'literacy',
    objective: 'Praticar o traçado de letras de forma com apoio visual progressivo.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'emerging',
      motorDemand: 'fine',
      scaffolding: 'Letras simples primeiro, guia pontilhado e tolerância progressiva.',
    },
    answers: ['I', 'L', 'T', 'V', 'A', 'E'],
    skillId: 'writing.trace-letter',
    secondarySkills: ['writing.copy-letter'],
    ages: [4, 7],
    interests: ['letters', 'writing', 'tracing'],
    playType: 'practice',
    permissions: [],
    experience: {
      fantasy: 'Oficina das letras',
      mechanic: 'trace-print-letter',
      interaction: 'draw',
      progression: { maxLevel: 6, adaptive: true },
      learningSignals: ['pathCoverage', 'shape'],
    },
  },
  {
    slug: 'cursive-letters',
    id: 'aprincar.cursive-letters',
    name: 'Oficina de Cursiva',
    description: 'Acompanhe movimentos contínuos e pratique letras e ligações da escrita cursiva.',
    mode: 'handwriting',
    variant: 'cursive',
    familyId: 'literacy',
    objective: 'Praticar movimentos contínuos da cursiva e ligações simples entre letras.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'emerging',
      motorDemand: 'fine',
      scaffolding: 'Começa com letras de um movimento e avança para pequenas ligações.',
    },
    answers: ['l', 'i', 'u', 'e', 'm', 'li', 'le', 'mi'],
    skillId: 'writing.cursive.trace',
    secondarySkills: ['writing.cursive.join'],
    ages: [6, 9],
    interests: ['letters', 'writing', 'cursive'],
    playType: 'practice',
    permissions: [],
    experience: {
      fantasy: 'Ateliê da cursiva',
      mechanic: 'trace-cursive',
      interaction: 'draw',
      progression: { maxLevel: 8, adaptive: true },
      learningSignals: ['pathCoverage', 'continuity'],
    },
  },
  {
    slug: 'guided-painting',
    id: 'aprincar.guided-painting',
    name: 'Pintura por Cores',
    description: 'Escolha tintas e pinte partes grandes seguindo cor e símbolo.',
    mode: 'paint',
    variant: 'guided',
    familyId: 'creative',
    objective: 'Combinar pistas visuais e cores enquanto pinta regiões grandes.',
    mobileFirst: true,
    ageDesign: {
      literacyDependency: 'none',
      motorDemand: 'low',
      scaffolding: 'Cor sempre acompanhada de símbolo; regiões grandes e pintura corrigível.',
    },
    skillId: 'perception.colors.match',
    secondarySkills: ['creativity.visual-expression'],
    ages: [3, 5],
    interests: ['paint', 'colors', 'creative'],
    playType: 'learning',
    permissions: [],
    experience: {
      fantasy: 'Livro de colorir',
      mechanic: 'paint-regions',
      interaction: 'tap',
      progression: { maxLevel: 5, adaptive: true },
      learningSignals: ['classification', 'visualChoice'],
    },
  },
];
